name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test ./...

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    # Set permissions for this job
    permissions:
      contents: write  # This is required for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o git-mcp-go-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o git-mcp-go-linux-arm64

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o git-mcp-go-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o git-mcp-go-darwin-arm64

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o git-mcp-go-windows-amd64.exe

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            git-mcp-go-linux-amd64
            git-mcp-go-linux-arm64
            git-mcp-go-darwin-amd64
            git-mcp-go-darwin-arm64
            git-mcp-go-windows-amd64.exe
          draft: false
          prerelease: false
